# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x08tutorial\"V\n\tHeroalarm\x12\r\n\x05\x65xsit\x18\x01 \x01(\x05\x1a:\n\x08Position\x12\n\n\x02ld\x18\x01 \x01(\x05\x12\n\n\x02rd\x18\x02 \x01(\x05\x12\n\n\x02ru\x18\x03 \x01(\x05\x12\n\n\x02lu\x18\x04 \x01(\x05\"\x1b\n\x08\x46lyslope\x12\x0f\n\x07\x46Salarm\x18\x01 \x01(\t\"\x1e\n\x0b\x45nergyorgan\x12\x0f\n\x07\x45Oalarm\x18\x01 \x01(\tb\x06proto3')



_HEROALARM = DESCRIPTOR.message_types_by_name['Heroalarm']
_HEROALARM_POSITION = _HEROALARM.nested_types_by_name['Position']
_FLYSLOPE = DESCRIPTOR.message_types_by_name['Flyslope']
_ENERGYORGAN = DESCRIPTOR.message_types_by_name['Energyorgan']
Heroalarm = _reflection.GeneratedProtocolMessageType('Heroalarm', (_message.Message,), {

  'Position' : _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
    'DESCRIPTOR' : _HEROALARM_POSITION,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Heroalarm.Position)
    })
  ,
  'DESCRIPTOR' : _HEROALARM,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Heroalarm)
  })
_sym_db.RegisterMessage(Heroalarm)
_sym_db.RegisterMessage(Heroalarm.Position)

Flyslope = _reflection.GeneratedProtocolMessageType('Flyslope', (_message.Message,), {
  'DESCRIPTOR' : _FLYSLOPE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Flyslope)
  })
_sym_db.RegisterMessage(Flyslope)

Energyorgan = _reflection.GeneratedProtocolMessageType('Energyorgan', (_message.Message,), {
  'DESCRIPTOR' : _ENERGYORGAN,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Energyorgan)
  })
_sym_db.RegisterMessage(Energyorgan)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEROALARM._serialized_start=27
  _HEROALARM._serialized_end=113
  _HEROALARM_POSITION._serialized_start=55
  _HEROALARM_POSITION._serialized_end=113
  _FLYSLOPE._serialized_start=115
  _FLYSLOPE._serialized_end=142
  _ENERGYORGAN._serialized_start=144
  _ENERGYORGAN._serialized_end=174
# @@protoc_insertion_point(module_scope)
